baseURL=https://dev.saral.pro/login
dashboardURL=https://dev.saral.pro/dashboard
productionurl=https://saral.pro/
productdashboardurl=https://accounts.saral.pro/dashboard/filelist
deducteeurl=https://devtds.saral.pro/tds/deductee
username=darshanbasavaraj1120@gmail.com
password=Darshan@123
chromepath=./Drivers\\chromedriver.exe
firefoxpath=./Drivers\\geckodriver.exe
iepath=./Drivers\\IEDriverServer.exe
LoginTestData=./src\\test\\java\\pro\\saral\\testData\\LoginData.xlsx
validstepper24Qexcel=./src/test/java/pro/saral/testData/BLRB00769G-TDSForm24Q1.xlsx
invalidstepper24Qexcel=./src/test/java/pro/saral/testData/BLRB00769G-TDSForm24Q1 -invalid.xlsx
24Qinvalidexcelfile=./src/test/java/pro/saral/testData/BLRK21135C-TDSForm26Q3.xlsx
24Qvalidexcel=./src/test/java/pro/saral/testData/BLRL03775C-TDSForm24Q1.xlsx
24qerrorexcelfile=./src/test/java/pro/saral/testData/BLRL03775C-TDSForm24Q1 - error.xlsx
24qvalidconso=./src/test/java/pro/saral/testData/BLRL03775C_202021_24Q_Q1.tds
24qvalidtext=./src/test/java/pro/saral/testData/Form24Q1.txt
24qmasterimport=./src/test/java/pro/saral/testData/BLRL03775C-TDSForm24Q1-Master import.xlsx
pdexcel=./src/test/java/pro/saral/testData/BLRL03775C-TDSForm24Q1-predict-default.xlsx



companyname=Saral_Pro
companyaddress=Rajajinagar
comapnyplace=Banglore
companysate=29
companypincode=560057
companygstin=29AABCU9603R1ZJ
companytds=BLRA00198C
companyemail=saral@gmail.com
companymobilenumber=9867360010
deductoralternatestdcode=txtdeductorStdcodeAlt
deductoralternatenumber=txtdeductorPhoneAlt
responsiblepersontab=//label[contains(text(),"Responsible Person's Details")]
responsiblepersonstd=txtpersonStdcodeAlt
responsiblepersonnumber=txtpersonPhoneAlt
26Qtab=//a[contains(text(),'26Q')]
26qdeduction=//a[@href='/26q/deduction']


Employee_Page_Xpaths
employeetab=Employee
addemployee=btn-addIcon-empDedMaster
empname=txt-name-emp
emppan=pan
empdesignation=txt-designation-emp
empmailid=txt-emailId
empaddress=txt-address-emp
emprefnum=txt-panRefNo-deductee
empcategory=ddl-taxCategory-emp
empsave=btn-ModalSaveUpdate-emp
empdelete=Del-Emp-Ded

Deductee_Page_Xpaths
search=//input[@id='entiry-search']
entity=Saral_Pro_Test
client=//tbody/tr[2]/td[3]/div[1]
fydropdown=ddl-form2022
quarter=ddl-quar1
type=ddl-usr0
deducteetab=deductee
deducteeadd=btn-addIcon-empDedMaster
deducteename=txt-Name-deductee
deducteerefnum=txt-panRefNo-deductee
deducteerefnumerror=//span[contains(text(),'Ded Ref.No must be 10 Characters')]
deducteepan=//input[@placeholder='Select or Search']
deducteecode=ddl-DeducteeCode-deductee
confirmdeducteecode=btn-deductee-OK
deducteeaddress=txt-address-emp
deducteestate=ddl-stateCode-deductee
deducteeemailid=txt-DED-EmailID
206abapplicablecheckbox=(//div[@class='check-container'])[3]
deductesave=btn-ModalSaveUpdate-emp
deducteesavenotification=//div[contains(text(),'Saved Successfully')]
nameerrormessage=(//div/div/span[contains(text(),'Field required')])[1]
panerrormessage=(//div/div/span[contains(text(),'Field required')])[2]
codeerrormessage=(//div/div/span[contains(text(),'Field required')])[3]
invaliddeducteepanverify=//span[contains(text(),'First 5 are character, next 4 are digits and last ')]
invalidrefnumverify=(//div/button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger Ripple-parent'])[3]
invalidemailerror=(//div/button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger Ripple-parent'])[5]
invalidemailerrorverify=//span[contains(text(),'Invalid email')]
deducteeclose=(//button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger btn-sm Ripple-parent'])[4]
panalreadyexist=//div[contains(text(),'PAN Number Already Exists.')]
editdeductee=btn-editIcon-EmpTable-0
deducteeupdatenotification=//div[contains(text(),'Updated Successfully')]
singlecheckbox=(//label[@class='checkbox checkbox-primary'])[2]
bulkcheckbox=(//label[@class='checkbox checkbox-primary'])[1]
deletedeductee=Del-Emp-Ded
confirmdelete=//button[@class='btn2 button2 btn-danger btn-sm Ripple-parent']
deducteedeletenotification=//div[contains(text(),'Deleted Successfully')]
deductiondeletenotification=//div[contains(text(),'Deleted Successfully!')]

Settings_Page_Xpaths
settingstab=OptionSettings
24qcheckbox=//span[contains(text(),'Form 24Q')]
26qcheckbox=//span[contains(text(),'Form 26Q')]
27qcheckbox=//span[contains(text(),'Form 27Q')]
27Eeqcheckbox=//span[contains(text(),'Form 27EQ')]
settingssave=optSave
tdstab=//a[contains(text(),'24Q')]/preceding-sibling::a
24qtab=//a[contains(text(),'24Q')]
26qtab=//a[contains(text(),'26Q')]
27qtab=//a[contains(text(),'27Q')]
27eqtab=//a[contains(text(),'27EQ')]
exittour=//button[contains(text(),'Exit Tour Mode')]

Challan_Page_Xpaths
challantab=challan
addchallan=btn-add-challan
challanincometax=txt-incomeTaxAmt
challansurge=txt-surchargeAmt
challancess=txt-cessAmt
challaninterest=txt-interestAmt
challanotheramount=txt-othersAmt
challanfee=txt-fee234
challantdsothers=txt-othersAmtDd
challantdsinterest=txt-interestAmtDd
challantotal=txt-totalAmtDd
challansection=id
challantypeofpaymrnt=ddl-minorHead
bankchallanno=txt-bankChallanDdoNo
challanpaiddateofchallan=dateOfChallanVoucher
challanbsrcode=txt-bsrOrRecptNo
challancompanies=//div[@class='check-container']
challanremarks=txt-Remarks
challancompanies=(//div[@class='check-container'])[1]
challanprint=challan-prints
downloadchallan=//span[contains(text(),'Download')]//parent::button
closechallanprint=(//button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger btn-sm Ripple-parent'])[3]
challanback=challan-close-btn
challansave=challan-submit-btn
challansectionabbr=sectionAbbr
challanselectall=(//div[@class='check-container'])[1]
singlechallanselect=(//div[@class='check-container'])[2]
challanedit=//button[@id='btn-edit-challanTable-0']
deletechallan=//button[@id='btn-delete-challan']
pickdeduction=btn-from-deduction-challan
challanprint=challan-prints
challanpreviewdownload=(//button[@class='btn2 button2 btn-primary btn-sm Ripple-parent'])[10]
closechallanpreview=(//div[@data-title='Close'])[3]
closedeleteconfirm=(//div[@data-title='Close'])[5]
errormessage=(//div/div/span[contains(text(),'Field required')])[4]
errorclick1=(//div/button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger Ripple-parent'])[1]
errorclick2=(//div/button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger Ripple-parent'])[2]
errorclick3=(//div/button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger Ripple-parent'])[3]
errorclick4=(//div/button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger Ripple-parent'])[4]
errorclick5=(//div/button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger Ripple-parent'])[5]
errorclick6=(//div/button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger Ripple-parent'])[6]
errorclick7=(//div/button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger Ripple-parent'])[7]
errorclick8=(//div/button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger Ripple-parent'])[8]
errorclick9=(//div/button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger Ripple-parent'])[9]
errorclick10=(//div/button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger Ripple-parent'])[10]
invaliddateerror=//span[contains(text(),'Invalid date')]
invalidamount1=(//span[contains(text(),'Invalid Amount')])[1]
invalidamount2=(//span[contains(text(),'Invalid Amount')])[2]
invalidamount3=(//span[contains(text(),'Invalid Amount')])[3]
invalidamount4=(//span[contains(text(),'Invalid Amount')])[4]
invalidamount5=(//span[contains(text(),'Invalid Amount')])[5]
invalidamount6=(//span[contains(text(),'Invalid Amount')])[6]
invalidamount7=(//span[contains(text(),'Invalid Amount')])[7]
invalidtdsinterest=//span[contains(text(),'Amount can not be greater than Interest Amount')]
invalidbsrcode=//span[contains(text(),'Exact 7 degits required!')]
invalidbankchallanno=//span[contains(text(),'Exact 5 digits we need')]
confirmback=(//button[@class='btn2 button2 btn-primary btn-sm Ripple-parent'])[5]
amountavailableofchallan=//span[contains(text(),'Amount Avbl.: Rs. 10340')]
challanwarning=(//button[@class='btn2 button2 btn-primary btn-sm Ripple-parent'])[4]

Deduction_Page_Xpaths
deductiontab=deduction
adddeduction=btn-add-deduction
addnewemployee=add-newempded
deducteeclick=//li[contains(text(),'Kiran (NYUPF6764N)')]
deductionname=txt-employeeId
deductionsection=ddl-sectionAbbr-deduction
deductionremark=ddl-remarks1-deduction
deductionamount=text-paidAmt-null
deductionpaiddate=rDatePickerId-dtf-ded-paidDate
deductionincometaxrate=text-incomeTaxRate-null
deductionincometax=text-incomeTaxAmt-null
deductionsurgerate=text-surchargeRate-null
deductionsurgeamount=text-surchargeAmt-null
deductioncessrate=text-cessRate-null
deductioncessamount=text-cessAmt-null
deductiontotaltax=text-totalTaxAmt-null
invalidamount=//*[contains(text(),'Invalid Amount - 2.312312122312')]
deducteddate=rDatePickerId-dtf-deduction-deductedDate
confirmclear=(//button[@class='btn2 button2 btn-primary btn-sm Ripple-parent'])[12]
us197certno=txt-certificate197-deduction
challanserialno=txt2-serialNo-deduction
selectlinkchallan=txt2-serialNo-deduction-ul
challanpaiddate=rDatePickerId-dtf-dateOfChallanVoucher-deductedDate
deductionbankchallanno=txt-bankChallanDdoNo-deduction
bsrcode=txt-bsrOrRecptNo-deduction
certnoverification=//span[contains(text(),'Not Verified')]
challantotal=txt-totalAmt-deduction
amountavailable=Amount Avbl Rs. 0.00
deductionbackbutton=Deductions-back-btn
deductionclearbutton=Deductions-clear-btn
deductionsavebutton=Deductions-submit-btn
deductiondelete=btn-delete-challan
employeeclick=//li[contains(text(),'Kiran (NUYPS7787N)')]
employeetestclick=//li[contains(text(),'Test (NAKPF7838N)')]
editfirstdeduction=btn-edit-Deductions-0
employeeclick2=//li[contains(text(),'Arun (PANINVALID)')]
anotheremployee=//*[@id="txt-employeeId-ul"]/li[1]
certificatenoerror=//span[contains(text(),'Exact 10 alphabets and numbers required')]
totaltaxerrormessage=//span[contains(text(),'Tax Amount Can not be greaterthan Amount Of Paymen')]
surgerateerror=//span[contains(text(),'Max rate allow 99.99% only')]
totalamounterror=//span[contains(text(),'Tax Amount Can not be greaterthan Amount Of Payment')]
invalidsurgeamount=//span[contains(text(),'Invalid Amount - 3.462837648273')]
invalidamount26q=//span[contains(text(),'Invalid Amount - 34628376482734')]
confirmbutton=(//button[@class='btn2 button2 btn-primary btn-sm Ripple-parent'])[6]
pickdeductionaddchallan=(//button[@class='btn2 icon-btn2 btn-primary Ripple-parent'])[2]
selectdeduction=//input[@id='chk-Deductions-0']//following-sibling::span
verifyincometax=//input[@value='1000']
verify26qincometax=(//input[@value='2020'])
verifysurge=(//input[@value='20'])[1]
verify26qsurge=(//input[@value='10'])
clickbsrcode=//li[contains(text(),'2311323')]
verifycess=(//input[@value='20'])[2]
verify26qcess=(//input[@value='41'])
verifytdstotal=//input[@value='1040']
verify26qtdstotal=(//input[@value='2071'])
createchallan=btn-fromDeduction
createchalla=//button[@id='btn-romDeduction']
challandeductionnotification=challan-formdeduction-Notification
deductioneditdeduction=btn-edit-Deductions-1
firstdeductionedit=btn-edit-Deductions-0
copydecuction=Deductions-as-new-btn
confirmdeleteagain=(//button[@class='btn2 button2 btn-danger btn-sm Ripple-parent'])[2]
searchname=Name-firstCondition-value
clicksearch=Name-filter-btn
searchnameclick=Name-search-btn
pickdeductionbsrcode=txt-bsrOrRecptNoSingleCln

Challan_Mapping_Page_Xpaths
challanmappingtab=challanMapping
challanmappingcheckbox=(//div[@class='check-container'])[2]
mapbutton=challan-mapping-save
autoadjust=challan-mapping-auto-adjust
selecteddeduction=//span[@class='formdeduction__dropdown___2n9zt flex align-items-center mr-1 undefined ']
allchallanscheckbox=(//span[@class='switch__slider___2GQX9 switch__round___24X4n'])[2]
linkeddeductioncheckbox=(//span[@class='switch__slider___2GQX9 switch__round___24X4n'])[1]
allchallans=(//span[@class='switch__slider___2GQX9 switch__round___24X4n'])[2]
mappedtab=//div[@class='styles__tab___59Jbl Small-Body-CopySmall-body-Primary false']
unmappedtab=//div[@class='styles__tab___59Jbl Small-Body-CopySmall-body-Primary styles__active___1KJ6l']
unlinkallbutton=(//button[@class='btn2 button2 btn-primary btn-sm Ripple-parent'])[9]
unlinkbutton=//button[@class='btn2 button2 btn-danger btn-sm Ripple-parent']
unlinkcheckbox=(//div[@class='check-container'])[1]
confirmunlink=(//button[@class='btn2 button2 btn-primary btn-sm Ripple-parent'])[10]
selectchallan=//li[contains(text(),'1;24Q;Q1')]


Excel_Import_Xpaths
consooldfileconfirmation=(//button[@class='btn2 button2 btn-secondary btn-sm Ripple-parent'])[1]
predictdefaulttab=predictdefaults
importtab=import
excelimport=(//button[@id='import-button'])[1]
uploadbutton=(//button[@class='btn2 button2 btn-primary Ripple-parent'])[1]
uploadfile=file
prdictdefaultoption=//span[contains(text(),'Predict Defaults')]
shortpaymentview=//div[contains(text(),'Short Payment')]//following-sibling::div//child::div[@class='screens__DetailsTypeButton___CfQA4']
shortpaymentverify=//span[contains(text(),'22946')]
bsrcodeverify=//td[contains(text(),'6390340')]
predictdefaultback=//span[contains(text(),'Back')]//parent::button
latepaymentinterestview=//div[contains(text(),'Late Payment Interest')]//following-sibling::div//child::div[@class='screens__DetailsTypeButton___CfQA4']
pannumberverify=(//td[contains(text(),'AENPT5928F')])[2]
latepaymentinterestverify=//span[contains(text(),'1447.5')]
panstatusverify=//td[contains(text(),'AENPT5928F')]//following-sibling::td/div[contains(text(),'Not Verified')]
numberofpan=//div[contains(text(),'PAN Status')]//following-sibling::div/div/span/span[contains(text(),'6')]
panstatus=//div[contains(text(),'PAN Status')]//following-sibling::div//child::div[@class='screens__DetailsTypeButton___CfQA4']
challanstatus=//div[contains(text(),'Challan Status')]//following-sibling::div//child::div[@class='screens__DetailsTypeButton___CfQA4']
challnumberverify=//td[contains(text(),'00094')]//following-sibling::td[contains(text(),'Not Verified')]
HigherRateDeductionsstatus=//div[contains(text(),'Higher Rate Deductions')]//following-sibling::div//child::div[@class='screens__DetailsTypeButton___CfQA4']
ChallanDeductionMappingStatusview=//div[contains(text(),'Challan Deduction Mapping Status')]//following-sibling::div//child::div[@class='screens__DetailsTypeButton___CfQA4']
higherrateverifynameverify=//div[contains(text(),'Anil')]//parent::td//following-sibling::td[contains(text(),'PAN Not available - Higher Rate (20%)')]
higherrateverify=//span[contains(text(),'Deductions with higher Rate')]
editdeduction=btn-edit-Deductions-4
deletechallanindeduction=delete-deduction-
paginationmax=//button[contains(text(),'25')]
mappedprice=//span[contains(text(),'Mapped: Rs.51398')]
unmappedprice=//span[contains(text(),'Un-Mapped: Rs.9060')]
unmappedemployee=//div[contains(text(),'AYESHA SIDDIQUA')]

EReturn_Xpath
ereturntab=eReturn
generatefuvbutton=//span[contains(text(),'Generate FVU')]//parent::button
viewerror=//body/div[@id='root']/div[3]/div[2]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[1]/div[2]/div[5]/div[2]/div[3]/div[2]/*[1]
viewerroredit=//button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-secondary btn-sm Ripple-parent']
closeerror=(//button[@class='btn2 icon-btn2 btn-rounded btn-flat btn-danger btn-sm Ripple-parent'])[5]
verifyerrorone=//span[contains(text(),'T-FV-2063 Valid Count of Challan/Transfer Voucher ')]
verifyerrortwo=//span[contains(text(),"T-FV-2223 Invalid value provided under field 'Resp")]
veifyerrorthree=(//td[contains(text(),'Batch')])[1]
verifyerrorfour=(//td[contains(text(),' Regular ')])[1]
verifyerrorfive=//td[contains(text(),'Count of Challan/transfer voucher Records ')]
ereturnvalidation=//span[contains(text(),'File validation(Form 24Q- Quarter 2) was successfu')]
ereturnerrorvalidation=//span[contains(text(),'to va')]
editdeductor=deductor-edit-bdg
deductorname=txtnameOfDeductor
deductorsave=r-deductor-submit-btn
savesettings=(//span[contains(text(),'Save')]//parent::button)[2]